services:
  - type: web
    name: tinglov
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CAPTCHA_SECRET
        generateValue: true
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ADMIN_PATH
        sync: false
      - key: VITE_ADMIN_PATH
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: CLOUDFLARE_R2_URL
        sync: false
      - key: VITE_CLOUDFLARE_R2_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false


